### ISSUE TITLE
Generating BLEU Score

### ISSUE THREAD

**Issue by Jbiloki** [facebookresearch/TreeNLG#7] opened 2020-05-24 00:31 UTC
Are there any instructions on generating the bleu score for the weather task? My output for running the commands in the readme after generating is the tree scores but I don't get any .tsv in order to run the bleu score evaluation.

I am also only getting `gen.constr.txt` as output rather than a tsv file or the expected gen.txt. Any guidance would be great, until then I will try to find my own solution as well.

**Comment by Jbiloki** [comment] 2020-05-24 21:56
The gen.txt issue still persists but the bleu score can be generated given the right modules that I had to find through overriding the shell script to not output to null in order to see what I need. If you make a clean environment for this repo here's my `pip freeze` in order to get it running

```certifi==2020.4.5.1
cffi==1.14.0
click==7.1.2
cycler==0.10.0
Cython==0.29.19
decorator==4.4.2
-e git+https://github.com/pytorch/fairseq.git@3822db33002f18f64cb9eb7b154ee5c76de87d5b#egg=fairseq
future==0.18.2
imagecodecs==2020.2.18
imageio==2.8.0
joblib==0.15.1
kiwisolver==1.2.0
matplotlib==3.2.1
networkx==2.4
nltk==3.5
numpy==1.18.4
Pillow==7.1.2
portalocker==1.7.0
pycparser==2.20
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
regex==2020.5.14
sacrebleu==1.4.9
scikit-image==0.17.2
scipy==1.4.1
six==1.15.0
tifffile==2020.5.11
torch==1.5.0
tqdm==4.46.0
typing==3.7.4.1```

**Comment by znculee** [comment] 2020-07-13 03:46
We evaluate the BLEU score by [tuetschek/e2e-metrics](https://github.com/tuetschek/e2e-metrics) by default. It will be cloned if you don't have it. Then you should run `pip install -r requirements.txt` under the cloned e2e-metrics repo to install the necessary requirements. Then the [score measuring code](https://github.com/facebookresearch/TreeNLG/blob/e66e0123dd2eec6f9e25ed3f1cf935ddf15ff2af/scripts/generate.weather.lstm.sh#L33) should be fine to run.

**Comment by mwhite14850** [comment] 2020-07-19 16:39
I'm going to go ahead and close this issue, but feel free to reopen it (or open a new issue) if Xintong's message doesn't suffice.

**Closed as completed by mwhite14850** 2020-07-19 16:39 UTC

**Comment by Jbiloki** [comment] 2020-07-26 00:03
Is it possible to upload your python version/requirements.txt for your main repo this is very ambiguous and I have not been able to reproduce your results.

**Comment by Jbiloki** [comment] 2020-07-26 06:29
I also have trouble using the .sh files on a mac since readlink acts differently: `readlink: illegal option -- f` any advice would help.

**Comment by znculee** [comment] 2020-07-26 23:54
@Jbiloki 

> Is it possible to upload your python version/requirements.txt for your main repo this is very ambiguous and I have not been able to reproduce your results.

Since I have no push permission for this repo, I'd like to paste my `requirements.txt` below. Note that some of the packages are installed locally as said in the README, so, please don't use it directly with `pip` or `conda`, but just use it as a reference.

> I also have trouble using the .sh files on a mac since readlink acts differently: `readlink: illegal option -- f` any advice would help.

You may use `greadlink` on mac to achieve the same function on Linux by installing `coreutils` with `brew`. [(see reference here)](https://stackoverflow.com/a/4031502/11583398)

---

`requirements.txt`
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
astroid=2.3.3=py37_0
backcall=0.1.0=pypi_0
blas=1.0=mkl
boto3=1.12.45=pypi_0
botocore=1.15.45=pypi_0
ca-certificates=2020.1.1=0
certifi=2020.4.5.1=py37_0
cffi=1.13.2=py37h2e261b9_0
chardet=3.0.4=pypi_0
click=7.1.1=pypi_0
cudatoolkit=10.1.243=h6bb024c_0
cycler=0.10.0=pypi_0
cython=0.29.14=pypi_0
decorator=4.4.1=pypi_0
docutils=0.15.2=pypi_0
fairseq=0.9.0=dev_0
filelock=3.0.12=pypi_0
freetype=2.9.1=h8a8886c_1
future=0.18.2=pypi_0
idna=2.9=pypi_0
imageio=2.6.1=pypi_0
intel-openmp=2020.0=166
ipdb=0.12.3=pypi_0
ipython=7.12.0=pypi_0
ipython-genutils=0.2.0=pypi_0
isort=4.3.21=py37_0
jedi=0.17.0=pypi_0
jmespath=0.9.5=pypi_0
joblib=0.14.1=pypi_0
jpeg=9b=h024ee3a_2
kiwisolver=1.1.0=pypi_0
lazy-object-proxy=1.4.3=py37h7b6447c_0
ld_impl_linux-64=2.33.1=h53a641e_7
libedit=3.1.20181209=hc058e9b_0
libffi=3.2.1=hd88cf55_4
libgcc-ng=9.1.0=hdf63c60_0
libgfortran-ng=7.3.0=hdf63c60_0
libpng=1.6.37=hbc83047_0
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.1.0=h2733197_0
matplotlib=3.1.3=pypi_0
mccabe=0.6.1=pypi_0
mkl=2020.0=166
mkl-service=2.3.0=py37he904b0f_0
mkl_fft=1.0.15=py37ha843d7b_0
mkl_random=1.1.0=py37hd6b4f25_0
ncurses=6.1=he6710b0_1
networkx=2.4=pypi_0
ninja=1.9.0=py37hfd86e86_0
nltk=3.4.5=pypi_0
numpy=1.18.1=py37h4f9e942_0
numpy-base=1.18.1=py37hde5b4d6_1
olefile=0.46=py37_0
openssl=1.1.1g=h7b6447c_0
parso=0.7.0=pypi_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pillow=7.0.0=py37hb39fc2d_0
pip=20.0.2=py37_1
portalocker=1.5.2=pypi_0
prompt-toolkit=3.0.3=pypi_0
protobuf=3.11.3=pypi_0
ptyprocess=0.6.0=pypi_0
pycparser=2.19=py37_0
pygments=2.5.2=pypi_0
pylint=2.4.4=py37_0
pyparsing=2.4.6=pypi_0
python=3.7.6=h0371630_2
python-dateutil=2.8.1=pypi_0
pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
pywavelets=1.1.1=pypi_0
readline=7.0=h7b6447c_5
regex=2020.1.8=pypi_0
requests=2.23.0=pypi_0
s3transfer=0.3.3=pypi_0
sacrebleu=1.4.3=pypi_0
sacremoses=0.0.41=pypi_0
scikit-image=0.16.2=pypi_0
scipy=1.4.1=pypi_0
sentencepiece=0.1.85=pypi_0
setuptools=45.1.0=py37_0
six=1.14.0=py37_0
sqlite=3.31.1=h7b6447c_0
tensorboardx=2.0=pypi_0
tk=8.6.8=hbc83047_0
tokenizers=0.5.2=pypi_0
torchvision=0.5.0=py37_cu101
tqdm=4.42.1=pypi_0
traitlets=4.3.3=pypi_0
transformers=2.8.0=pypi_0
typed-ast=1.4.1=pypi_0
typing=3.7.4.1=pypi_0
urllib3=1.25.9=pypi_0
wcwidth=0.1.8=pypi_0
wheel=0.34.2=py37_0
wrapt=1.11.2=pypi_0
xz=5.2.4=h14c3975_4
zlib=1.2.11=h7b6447c_3
zstd=1.3.7=h0b5b093_0
```

**Comment by Jbiloki** [comment] 2020-07-27 01:03
Thanks for your help, I will see if I can reproduce with these versions.

**Comment by Jbiloki** [comment] 2020-07-27 01:25
Following these steps I am able to train/eval a model but the BLEU is much higher than reported. Has this improved over time?

Output:

```SCORES:                                                                                                                                                                                 
==============
BLEU: 0.9224
NIST: 7.7533
METEOR: 0.6585
ROUGE_L: 0.8507
CIDEr: 6.2801

Tree accuracy: 99.94 (3119 / 3121)
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
EOF encountered in a comment.
Failure rate: 0.00 (0 / 0)
scripts/generate.weather.lstm.sh: line 27: ggreadlink: command not found

replacing failures from 
Usage: measure_scores hypothesis reference baseline
Usage: tree_acc hypothesis baseline```

**Comment by znculee** [comment] 2020-07-27 01:32
The scores can be slightly different as reported because of some new features. But a 90+ BLEU is not expected on all these three datasets. Please refer to the scores I tested below.
```
Dataset   | Method    | discourse |         | no-discourse |         | whole
          |           | BLEU      | TreeAcc | BLEU         | TreeAcc | TreeAcc
--        | --        | --        | --      | --           | --      | --
Weather   | S2S-Tree  | 74.51     | 89.65   | 76.34        | 94.17   | 93.59
          | +constr   | 75.41     | 100.0   | 76.88        | 99.84   | 99.86
          | +replfail | 75.41     | 100.0   | 77.38        | 99.84   | 99.86
--        | --        | --        | --      | --           | --      | --
Weather   | S2S-Tree  | N/A       | N/A     | 77.79        | 94.09   | N/A
Challenge | +constr   | N/A       | N/A     | 78.52        | 99.91   | N/A
          | +replfail | N/A       | N/A     | 79.02        | 99.91   | N/A
--        | --        | --        | --      | --           | --      | --
E2E       | S2S-Tree  | 66.70     | 62.17   | 77.37        | 96.72   | 95.10
          | +constr   | 64.32     | 99.13   | 77.44        | 99.89   | 99.86
          | +replfail | 65.38     | 99.13   | 77.43        | 99.89   | 99.86
```

**Comment by Jbiloki** [comment] 2020-07-27 02:00
Right, the scores I am getting don't make much sense. Do you know what must be changed in order to reproduce those numbers?

**Comment by znculee** [comment] 2020-07-27 02:06
I'm not sure what you should change in your experiments. But following the steps in README, you should be able to reproduce the above scores. Feel free to ask if you have a specific question.

**Comment by Jbiloki** [comment] 2020-07-28 05:19
I ran the steps in the README twice and get unrealistic BLEU numbers each time. I am creating a new virtual environment. Checking out and building commit `-e git+https://github.com/pytorch/fairseq.git@3822db33002f18f64cb9eb7b154ee5c76de87d5b#egg=fairseq` 

getting the submodules with `git submodule update --init --rercursive`

And running these three commands after updating the shell scripts with appropriate mac analogs to readlink/grep:

```
bash scripts/prepare.weather.sh
bash scripts/train.weather.lstm.sh
bash scripts/generate.weather.lstm.sh
```
I should also note I am building on python version `3.6.10`

Am I overlooking something?

**Comment by mwhite14850** [comment] 2020-07-28 13:39
You could get unrealistically high scores if the bracketing tokens are not
removed before calculating BLEU.  The rmtreeinfo filter in the
various measure_scores scripts are supposed to take care of this.  Perhaps
worth checking whether this filter is working correctly.

**Comment by znculee** [comment] 2020-07-28 14:05
@mwhite14850 points out the problem. I've just tested with disabling `rmtreeinfo` in `measure_scores.sh`, it gives a 92.14 BLEU score for constrained decoding on weather dataset, but normally it should be 76.88.

**Comment by Jbiloki** [comment] 2020-07-29 06:47
Okay so looking at the output of `cat $hyp` in `measure_scores.sh` it looks like it does not remove brackets on mac. Here's a sample:

```
[__DS_JOIN__ [__DG_NO__ No , [__DG_INFORM__ [__ARG_LOCATION__ in [__ARG_CITY__ __ARG_CITY__ , [__ARG_REGION__ __ARG_REGION__ , [__ARG_COUNTRY__ __ARG_COUNTRY__ , it won't [__ARG_CONDITION_NOT__ rain [__ARG_DATE_TIME__ [__ARG_COLLOQUIAL__ next [__ARG_WEEKDAY__ __ARG_WEEKDAY__ . [__DG_INFORM__ Expect a high of [__ARG_TEMP_HIGH__ __ARG_TEMP_HIGH__ and a low of [__ARG_TEMP_LOW__ __ARG_TEMP_LOW__ , with [__ARG_CONDITION__ light fog
[__DS_JOIN__ [__DG_NO__ No , [__DG_INFORM__ it won't [__ARG_CONDITION_NOT__ snow [__ARG_DATE_TIME__ [__ARG_COLLOQUIAL__ today . [__DG_INFORM__ Expect a high of [__ARG_TEMP_HIGH__ __ARG_TEMP_HIGH__ and a low of [__ARG_TEMP_LOW__ __ARG_TEMP_LOW__ , with [__ARG_CLOUD_COVERAGE__ mostly cloudy skies
[__DG_NO__ No , [__DS_JUSTIFY__ [__DG_RECOMMEND__ you don't need a [__ARG_ATTIRE_NOT__ jacket because [__DG_INFORM__ it won't be [__ARG_CONDITION_NOT__ cold [__ARG_DATE_TIME__ [__ARG_COLLOQUIAL__ today . [__DG_INFORM__ Expect a high of [__ARG_TEMP_HIGH__ __ARG_TEMP_HIGH__ and a low of [__ARG_TEMP_LOW__ __ARG_TEMP_LOW__ with [__ARG_CLOUD_COVERAGE__ scattered clouds
[__DS_JOIN__ [__DG_NO__ No , [__DG_INFORM__ it will not be [__ARG_CONDITION_NOT__ cloudy [__ARG_DATE_TIME__ [__ARG_COLLOQUIAL__ today [__ARG_LOCATION__ in [__ARG_CITY__ __ARG_CITY__ , [__ARG_REGION__ __ARG_REGION__ . [__DG_INFORM__ It will be [__ARG_CLOUD_COVERAGE__ mostly sunny with a high of [__ARG_TEMP_HIGH__ __ARG_TEMP_HIGH__ and a low of [__ARG_TEMP_LOW__ __ARG_TEMP_LOW__
[__DG_YES__ Yes , [__DG_INFORM__ [__ARG_DATE_TIME__ [__ARG_WEEKDAY__ __ARG_WEEKDAY__ will be [__ARG_CLOUD_COVERAGE__ mostly cloudy with a [__ARG_PRECIP_CHANCE_SUMMARY__ very low chance of [__ARG_CONDITION__ thunderstorms and rain
[__DG_YES__ Yes , [__DG_INFORM__ expect a [__ARG_PRECIP_CHANCE_SUMMARY__ slight chance of [__ARG_CONDITION__ light rain [__ARG_DATE_TIME__ [__ARG_COLLOQUIAL__ today , with a [__ARG_CLOUD_COVERAGE__ funnel cloud
```

I also get this as the final output of the script:
`replacing failures from /Users/nguyen/src/npp/TreeNLG/checkpoints/weather.lstm/gen.txt
/Users/nguyen/src/npp/TreeNLG/checkpoints/weather.lstm/gen.txt does not exist`

**Comment by Jbiloki** [comment] 2020-07-29 07:02
I found the solution on mac in addition to needing `ggrep` and `greadlink` I also needed `gsed` once I have these gnu compatible versions I get correct scores. Thank you @znculee and @mwhite14850 for working with me though this.

```
==============
BLEU: 0.7782
NIST: 7.3731
METEOR: 0.5575
ROUGE_L: 0.7700
CIDEr: 5.1160
```
